version: 1

languages:
  source: en
  target:
    - es
    - fr

projects:
  - name: demo-json
    type: json
    dictionary: demo/json/[lang].json
  - name: demo-xcode
    type: xcode
    dictionary: demo/xcode/Localizable.xcstrings
  - name: demo-yaml
    type: yaml
    dictionary: demo/yaml/[lang].yml
  - name: demo-yaml-root-key
    type: yaml-root-key
    dictionary: demo/yaml-root-key/[lang].yml
  - name: demo-markdown
    type: markdown
    dictionary: demo/markdown/[lang].md