name: Replexica
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  checks: write
  actions: write
  issues: write
jobs:
  localize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Replexica
        uses: replexica/github-action@main
        env:
          REPLEXICA_API_KEY: ${{ secrets.REPLEXICA_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
